const food = "I am from fruit scope....";
console.log(food);

// here the food variable is same in both files.
// but no conflicts...
// why?? Its because node js follows the conept of IIFE...
// Check IIFE file for more...
