const myFood = require("./myFood");

console.log(myFood.getName());
myFood.setName("Teheri....");
console.log("Setting new food to teheri.......");
console.log(myFood.getName());

/// here if I require the myFood module again....
// it should turn into kacchi Biriani.......na????
// as we are requiring the module again....that same object would be initiated again newely...
// lets seeee.....

const myFoodAgain = require("./myFood");
console.log(myFoodAgain?.getName());
//  Holaaaa.... here the output is Teheri...
// Thats what the module caching does...
// when it sees you are requiring the same module
// it skips importing it again. and keeps the previous state....
